services:
  # --- Banco de Dados (Postgres) ---
  db:
    image: postgres:15-alpine
    container_name: store-db
    restart: unless-stopped
    volumes:
      - /srv/store/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=walletdb
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - store_net
    ports:
      - "5433:5432" # Porta externa 5433 (evita conflito 5432 do Crypto)

  # --- Backend (Django API) ---
  api:
    container_name: store-api
    build: ./backend
    command: sh -c "/entrypoint.sh && python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=*,store-api,localhost,127.0.0.1
      - DJANGO_ALLOWED_HOSTS=*
      - SQL_ENGINE=django.db.backends.postgresql
      - DB_NAME=walletdb
      - DB_USER=django
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=store-db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - store_net
    ports:
      - "8002:8000"

  # --- Frontend (Vite) ---
  web:
    container_name: store-web
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - store_net
    ports:
      - "3001:3000"

networks:
  store_net:
    driver: bridge